#pragma once
#include <JuceHeader.h>
#include <atomic>

namespace RawDub
{
class BassSynth
{
public:
    void prepare (double sampleRate);
    void trigger (int semitoneOffset = 0, float levelGain = 1.0f);
    void renderAdd (float* out, int numSamples);

    // One coherent voice, not two combined: sine oscillator -> saturation
    // -> lowpass -> envelope. Foundation/Character (a second, separately
    // generated sine layer, purely summed) was tried and rolled back -
    // heavier, but read as disconnected/lifeless. This tests the opposite
    // idea: harmonics generated BY shaping one source, rather than added
    // from a second one - every harmonic here comes from Drive acting on
    // this same sine, not from a separate oscillator.
    std::atomic<float> tuneHz    { 55.0f };    // oscillator base frequency
    // Default recalibrated 0.25 -> 0.15 by ear: 0 loses pitch legibility
    // entirely (pure low sine tones are notoriously hard to perceive as a
    // pitch), 0.25 read as distorted, 0.1 was clean but thin, distortion
    // onset was found around 0.18 - 0.15 sits in the clean/legible window.
    std::atomic<float> drive     { 0.15f };    // saturation before the filter - the only source of harmonics above the fundamental
    std::atomic<float> cutoffHz  { 1200.0f };  // lowpass filter cutoff
    std::atomic<float> resonance { 0.1f };     // filter resonance, 0-0.95
    // hold/plateau length - how long the note stays at full, stable level
    // before it would ever start fading. NOT a release-speed control: the
    // release itself is a short fixed internal tail (see releaseTau) so a
    // note that reaches the end of its hold ends cleanly rather than
    // slowly dying. In practice most notes get cut off by the next
    // trigger before this ever elapses, which is the point - "release
    // only when the note is explicitly finished."
    std::atomic<float> decayMs   { 2000.0f };  // hold/length, favour steadiness by default

private:
    void applyTrigger (int semitoneOffset, float levelGain);

    double sampleRate = 44100.0;
    bool active = false;
    double phase = 0.0;
    double t = 0.0;
    double freq = 55.0;
    double holdSeconds = 2.0;
    double triggerGain = 1.0;
    double driveAmt = 0.0;
    double currentAmpEnv = 0.0; // envelope value at the most recent sample, tracked so a choke can start from the true current level
    static constexpr double attackTau = 0.003;
    // short, fixed, not user-facing: once the hold genuinely runs out,
    // end promptly and cleanly instead of a long user-controlled fade
    static constexpr double releaseTau = 0.1;

    // Proper monophonic behaviour: retriggering while a previous note is
    // still sounding does NOT crossfade two overlapping signals (that
    // was the earlier approach - patched repeatedly, still audible as a
    // click, worse the longer Hold made the note likely to be caught at
    // full amplitude). Instead the current note's oscillator/filter keep
    // running unchanged, but its envelope is forced into a fast, fixed,
    // smooth (raised-cosine, no kink) release to true silence first. Only
    // once that choke completes does the new note actually start -
    // stop, then start, never both at once.
    static constexpr double chokeTau = 0.008;
    bool choking = false;
    double chokeStartAmp = 0.0;
    double chokeT = 0.0;
    int pendingSemitoneOffset = 0;
    float pendingLevelGain = 1.0f;

    // Reverted to 0.6 (was 0.85) - raising it made an existing click at
    // note onset more audible without adding "authority," so the extra
    // headroom wasn't the actual lever. Keep at 0.85+ only if later
    // measurements justify it once the click itself is understood.
    static constexpr double outputGain = 0.6;

    // state-variable filter (Chamberlin) state
    double svfLow = 0.0;
    double svfBand = 0.0;
    double svfF = 0.3;
    double svfQ = 0.5;
};
}
