#pragma once
#include <JuceHeader.h>
#include <atomic>

namespace RawDub
{
class BassSynth
{
public:
    void prepare (double sampleRate);
    // driveOverride/cutoffOverride: -1 (default) means "use the Drive/
    // Cutoff knob"; otherwise use this instead for this note - how a
    // Global Pattern's section-level voicing override feeds in (see
    // project_raw_dub_song_architecture memory: instrument params are
    // the track's base identity, Global Pattern overrides are section
    // variations). Same sentinel convention as SkankSynth's
    // sawMixOverride. Volume deliberately has no override yet - it's a
    // real-time mixing control, not a per-note voicing snapshot like
    // these two, and belongs to a future mixer/performance layer.
    void trigger (int semitoneOffset = 0, float levelGain = 1.0f, float driveOverride = -1.0f, float cutoffOverride = -1.0f);
    void renderAdd (float* out, int numSamples);
    void resetToDefaults(); // for "New Project" - restores every param to its shipped default

    // One coherent voice, not two combined: sine oscillator -> saturation
    // -> lowpass -> envelope. Foundation/Character (a second, separately
    // generated sine layer, purely summed) was tried and rolled back -
    // heavier, but read as disconnected/lifeless. This tests the opposite
    // idea: harmonics generated BY shaping one source, rather than added
    // from a second one - every harmonic here comes from Drive acting on
    // this same sine, not from a separate oscillator.
    std::atomic<float> tuneHz    { 55.0f };    // oscillator base frequency
    // Default recalibrated 0.25 -> 0.15 by ear: 0 loses pitch legibility
    // entirely (pure low sine tones are notoriously hard to perceive as a
    // pitch), 0.25 read as distorted, 0.1 was clean but thin, distortion
    // onset was found around 0.18 - 0.15 sits in the clean/legible window.
    std::atomic<float> drive     { 0.15f };    // saturation before the filter - the only source of harmonics above the fundamental
    std::atomic<float> cutoffHz  { 1200.0f };  // lowpass filter cutoff
    std::atomic<float> resonance { 0.1f };     // filter resonance, 0-0.95
    // hold/plateau length - how long the note stays at full, stable level
    // before it would ever start fading. NOT a release-speed control: the
    // release itself is a short fixed internal tail (see releaseTau) so a
    // note that reaches the end of its hold ends cleanly rather than
    // slowly dying. In practice most notes get cut off by the next
    // trigger before this ever elapses, which is the point - "release
    // only when the note is explicitly finished."
    std::atomic<float> decayMs   { 2000.0f };  // hold/length, favour steadiness by default

    // Research switch, NOT a permanent architecture decision - A/B test
    // between the current Drive (tanh saturation) harmonic engine and
    // locked audio-rate amplitude modulation. AM mode bypasses Drive and
    // the fixed warmth entirely so the two mechanisms are compared
    // cleanly, one at a time, not stacked. See AMExperiment.h/.cpp for
    // the original isolated version of this test.
    std::atomic<bool> useAMMode { false };

    // AM mode only. Ratio is deliberately NOT a free Hz value - it must
    // stay one of a small set of simple integer ratios (1, 2, or 3) so
    // the modulator's sidebands always land exactly on harmonics of the
    // fundamental. A free rate was tested in isolation (AMExperiment)
    // and confirmed to go inharmonic/gong-like off-ratio - "always
    // musical" here means the UI only ever offers ratios that can't do
    // that, not a wide-open knob with a "safe zone."
    std::atomic<float> amRatio { 1.0f };
    std::atomic<float> amDepth { 0.8f }; // AM mode only, 0-1, safe at any value

    std::atomic<float> volume { 1.0f }; // basic level balancing against Kick, 0-1, applied before the master limiter

private:
    // Locked 1:1 AM produces an asymmetric waveform - a brief high peak,
    // then a much quieter negative half-cycle - so at matching PEAK
    // amplitude it measured ~5dB quieter in RMS/perceived loudness than
    // Drive mode. Not a mixing choice: a fixed internal correction so
    // switching Drive<->AM is loudness-matched and the ear judges tone,
    // not volume. Deliberately NOT exposed as a control - Volume (above)
    // stays a pure Kick/Bass balance knob, this is a synthesis-mode
    // correction. If this overshoots headroom/clips against Kick once
    // actually heard, reduce the dB value here, don't add a UI control.
    static constexpr double amMakeupGainDb = 5.0;
    static constexpr double amMakeupGain = 1.7783; // 10^(amMakeupGainDb/20), precomputed to avoid a runtime pow() in the audio callback
    void applyTrigger (int semitoneOffset, float levelGain, float driveOverride, float cutoffOverride);

    double sampleRate = 44100.0;
    bool active = false;
    double phase = 0.0;
    double modPhase = 0.0; // AM mode only - locked to phase by amRatio, no independent drift
    double t = 0.0;
    double freq = 55.0;
    double amRatioSnapshot = 1.0;
    double amDepthSnapshot = 0.8;
    bool amModeSnapshot = false; // read once at trigger time, like every other param
    double holdSeconds = 2.0;
    double triggerGain = 1.0;
    double driveAmt = 0.0;
    double currentAmpEnv = 0.0; // envelope value at the most recent sample, tracked so a choke can start from the true current level
    static constexpr double attackTau = 0.003;
    // short, fixed, not user-facing: once the hold genuinely runs out,
    // end promptly and cleanly instead of a long user-controlled fade
    static constexpr double releaseTau = 0.1;

    // Proper monophonic behaviour: retriggering while a previous note is
    // still sounding does NOT crossfade two overlapping signals (that
    // was the earlier approach - patched repeatedly, still audible as a
    // click, worse the longer Hold made the note likely to be caught at
    // full amplitude). Instead the current note's oscillator/filter keep
    // running unchanged, but its envelope is forced into a fast, fixed,
    // smooth (raised-cosine, no kink) release to true silence first. Only
    // once that choke completes does the new note actually start -
    // stop, then start, never both at once.
    static constexpr double chokeTau = 0.008;
    bool choking = false;
    double chokeStartAmp = 0.0;
    double chokeT = 0.0;
    int pendingSemitoneOffset = 0;
    float pendingLevelGain = 1.0f;
    float pendingDriveOverride = -1.0f;
    float pendingCutoffOverride = -1.0f;

    // Reverted to 0.6 (was 0.85) - raising it made an existing click at
    // note onset more audible without adding "authority," so the extra
    // headroom wasn't the actual lever. Keep at 0.85+ only if later
    // measurements justify it once the click itself is understood.
    static constexpr double outputGain = 0.6;

    // state-variable filter (Chamberlin) state
    double svfLow = 0.0;
    double svfBand = 0.0;
    double svfF = 0.3;
    double svfQ = 0.5;
};
}
